line-length = 150
target-version = "py312"
fix = true
ignore = [
    "F722", # "Syntax error in forward annotation" (issues with tensor typing)
    "F821", # "undefined name" (issues with tensor typing)
]
