# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from es_torch.distributed import distributed_pb2 as distributed_dot_distributed__pb2

GRPC_GENERATED_VERSION = '1.67.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in distributed/distributed_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ESServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Hello = channel.unary_unary(
                '/distributed.ESService/Hello',
                request_serializer=distributed_dot_distributed__pb2.HelloRequest.SerializeToString,
                response_deserializer=distributed_dot_distributed__pb2.HelloResponse.FromString,
                _registered_method=True)
        self.Done = channel.unary_unary(
                '/distributed.ESService/Done',
                request_serializer=distributed_dot_distributed__pb2.DoneRequest.SerializeToString,
                response_deserializer=distributed_dot_distributed__pb2.DoneResponse.FromString,
                _registered_method=True)
        self.Heartbeat = channel.unary_unary(
                '/distributed.ESService/Heartbeat',
                request_serializer=distributed_dot_distributed__pb2.HeartbeatRequest.SerializeToString,
                response_deserializer=distributed_dot_distributed__pb2.HeartbeatResponse.FromString,
                _registered_method=True)
        self.SendState = channel.unary_unary(
                '/distributed.ESService/SendState',
                request_serializer=distributed_dot_distributed__pb2.SendStateRequest.SerializeToString,
                response_deserializer=distributed_dot_distributed__pb2.SendStateResponse.FromString,
                _registered_method=True)
        self.Subscribe = channel.unary_stream(
                '/distributed.ESService/Subscribe',
                request_serializer=distributed_dot_distributed__pb2.SubscribeRequest.SerializeToString,
                response_deserializer=distributed_dot_distributed__pb2.SubscribeResponse.FromString,
                _registered_method=True)


class ESServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Hello(self, request, context):
        """worker joins
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Done(self, request, context):
        """epoch is done
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Heartbeat(self, request, context):
        """worker heartbeat
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendState(self, request, context):
        """send state if server demands it
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Subscribe(self, request, context):
        """subscribe to server events
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ESServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Hello': grpc.unary_unary_rpc_method_handler(
                    servicer.Hello,
                    request_deserializer=distributed_dot_distributed__pb2.HelloRequest.FromString,
                    response_serializer=distributed_dot_distributed__pb2.HelloResponse.SerializeToString,
            ),
            'Done': grpc.unary_unary_rpc_method_handler(
                    servicer.Done,
                    request_deserializer=distributed_dot_distributed__pb2.DoneRequest.FromString,
                    response_serializer=distributed_dot_distributed__pb2.DoneResponse.SerializeToString,
            ),
            'Heartbeat': grpc.unary_unary_rpc_method_handler(
                    servicer.Heartbeat,
                    request_deserializer=distributed_dot_distributed__pb2.HeartbeatRequest.FromString,
                    response_serializer=distributed_dot_distributed__pb2.HeartbeatResponse.SerializeToString,
            ),
            'SendState': grpc.unary_unary_rpc_method_handler(
                    servicer.SendState,
                    request_deserializer=distributed_dot_distributed__pb2.SendStateRequest.FromString,
                    response_serializer=distributed_dot_distributed__pb2.SendStateResponse.SerializeToString,
            ),
            'Subscribe': grpc.unary_stream_rpc_method_handler(
                    servicer.Subscribe,
                    request_deserializer=distributed_dot_distributed__pb2.SubscribeRequest.FromString,
                    response_serializer=distributed_dot_distributed__pb2.SubscribeResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'distributed.ESService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('distributed.ESService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ESService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Hello(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/distributed.ESService/Hello',
            distributed_dot_distributed__pb2.HelloRequest.SerializeToString,
            distributed_dot_distributed__pb2.HelloResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Done(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/distributed.ESService/Done',
            distributed_dot_distributed__pb2.DoneRequest.SerializeToString,
            distributed_dot_distributed__pb2.DoneResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Heartbeat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/distributed.ESService/Heartbeat',
            distributed_dot_distributed__pb2.HeartbeatRequest.SerializeToString,
            distributed_dot_distributed__pb2.HeartbeatResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SendState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/distributed.ESService/SendState',
            distributed_dot_distributed__pb2.SendStateRequest.SerializeToString,
            distributed_dot_distributed__pb2.SendStateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Subscribe(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/distributed.ESService/Subscribe',
            distributed_dot_distributed__pb2.SubscribeRequest.SerializeToString,
            distributed_dot_distributed__pb2.SubscribeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
